### ISSUE TITLE
[MISSING] Instruction to copy/paste or write manually: import com.example.android.aboutme.databinding.ActivityMainBinding

### ISSUE THREAD

**Issue by ojedavidea** [udacity/andfun-kotlin-about-me#17]
https://github.com/udacity/andfun-kotlin-about-me/blob/a388fe160ab90a2d6260a1cc769f21582b8a4915/app/src/main/java/com/example/android/aboutme/MainActivity.kt#L25

**Comment by SudKul** [comment]
Hi @ojedavidea 
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion. 

I am going to close all your unanswered issues present in this repo.
